name: GitHub Pages
on:
  push:
    branches: 
      - main
concurrency: 
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    environment: 
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v2