name: Deploy Pages

on:
  push:
    branches: 
      - main
      - dev
  pull_request: 
    branches: 
      - main
      - dev
  workflow_dispatch: 
  
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deploy-github.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build

      # Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        id: deploy-cloudflare
        uses: cloudflare/pages-action@v1
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: 38794234ecc4906051a567a03b96d5bd
          projectName: deminearchiver
          directory: ./dist
          wranglerVersion: 3

      # GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deploy-github
        uses: actions/deploy-pages@v1